IF
	!Dead("tacprsp")
	!Global("TACPRSP_EMPTY","GLOBAL",10)
	OR(2)
		!InMyArea("tacprsp")
		Global("tb#prsp","MYAREA",0)
	!GlobalGT("tacturnMoveTo","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("tb#prsp","MYAREA",1)
		SetGlobal("tacturnMoveTo","GLOBAL",3)
		CreateCreature("tb#prsp",[1715.1020],0)
		Continue()
END

IF
	InMyArea("tacprsp")
	GlobalGT("tacturnMoveTo","GLOBAL",3)
THEN
	RESPONSE #100
		ActionOverride("tacprsp",DestroySelf())
		Continue()
END
