IF
	!Dead("tacprsp")
	!Global("TACPRSP_EMPTY","GLOBAL",10)
	OR(2)
		!InMyArea("tacprsp")
		Global("tb#prsp","MYAREA",0)
	!GlobalGT("tacturnMoveTo","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("tb#prsp","MYAREA",1)
		SetGlobal("tacturnMoveTo","GLOBAL",1)
		CreateCreature("tb#prsp",[420.189],1)
		Continue()
END

IF
	InMyArea("tacprsp")
	GlobalGT("tacturnMoveTo","GLOBAL",1)
THEN
	RESPONSE #100
		ActionOverride("tacprsp",DestroySelf())
		Continue()
END
